spring.application.name=skillgapanalyzer
spring.datasource.url=jdbc:mysql://localhost:3306/skillgapanalyzer
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.s3-bucket=skillgapanalyzer-resume-storage
aws.region=ap-south-1

groq.api-key=${GROQ_API_KEY}
groq.api-url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.1-8b-instant